development: &development
  adapter: mysql2
  database: <%= ENV['DB_DATABASE']%>
  encoding: utf8mb4
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
test:
  <<: *development
  database: good_night_app_test

staging: &staging
  <<: *development

production:
  <<: *staging
